name: MLOps Production Pipeline
on: [push]

permissions:
  contents: read
  packages: write

jobs:
  train-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install pandas scikit-learn joblib fastapi uvicorn

      - name: Train Model
        run: python3 train.py

      - name: Check Model Quality
        run: |
          python3 -c "
          with open('model_score.txt', 'r') as f:
              score = float(f.read())
          if score > 50000:
              exit(1)
          "

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # This tags the image with your github username/repo-name:latest
          tags: ghcr.io/${{ github.repository_owner }}/house-price-predictor:latest